---
# Pod は、Kubernetes 上でコンテナを動かす最小単位です。
# この例では、nginx コンテナを 1 つ起動します。
apiVersion: v1
kind: Pod

metadata:
  # Pod の名前です。
  # kubectl get pod で確認すると、この名前で表示されます。
  name: nginx-sample

spec:
  # Pod の中で起動するコンテナを定義します。
  containers:
    # コンテナの名前です。
    # Pod の中でコンテナを識別するために使います。
    - name: nginx-container

      # 使用するコンテナイメージです。
      # この例では nginx の 1.25.3 を使用します。
      image: nginx:1.25.3

      # コンテナに渡す環境変数を定義します。
      #
      # 今回は、値を直接書くのではなく、
      # Secret から取得して環境変数に設定します。
      env:
        # USERNAME という環境変数を作成します。
        - name: USERNAME

          # valueFrom は、値を別の Kubernetes リソースから取得する設定です。
          valueFrom:

            # Secret の指定したキーから値を取得します。
            secretKeyRef:
              # 参照する Secret の名前です。
              #
              # 下で定義している nginx-secret から値を取得します。
              name: nginx-secret

              # Secret の data にあるキー名です。
              #
              # data.username の値が、
              # コンテナの環境変数 USERNAME に設定されます。
              key: username

        # PASSWORD という環境変数を作成します。
        - name: PASSWORD

          # Secret から値を取得して環境変数に設定します。
          valueFrom:
            secretKeyRef:
              # 参照する Secret の名前です。
              name: nginx-secret

              # Secret の data にあるキー名です。
              #
              # data.password の値が、
              # コンテナの環境変数 PASSWORD に設定されます。
              key: password

---
# Secret は、パスワードやトークンなどの機密情報を管理するための
# Kubernetes リソースです。
#
# ConfigMap と似ていますが、Secret は機密情報向けに使います。
# ただし、data に書く値は暗号化ではなく Base64 エンコードです。
apiVersion: v1
kind: Secret

metadata:
  # Secret の名前です。
  #
  # Pod 側の secretKeyRef.name で
  # この名前を指定して参照します。
  name: nginx-secret

# Secret の種類です。
#
# Opaque は、ユーザーが自由にキーと値を定義できる
# 一般的な Secret の種類です。
type: Opaque

# Secret に保存するデータです。
#
# data に書く値は Base64 エンコードされた文字列にする必要があります。
data:
  # username というキーです。
  #
  # YWRtaW4= は Base64 エンコードされた値です。
  # デコードすると admin になります。
  username: YWRtaW4=

  # password というキーです。
  #
  # YWRtaW4xMjM= は Base64 エンコードされた値です。
  # デコードすると admin123 になります。
  password: YWRtaW4xMjM=